### PR TITLE
Implement show hover

### LINKED ISSUE #199: Implement show hover
[Show hover](https://code.visualstudio.com/api/language-extensions/programmatic-language-features#show-hovers) is an essential language server feature.

Would be nice, if we could add this.

### PR DESCRIPTION
**Pull request by soham4abc**
Fixes #199

### CODE REVIEW

**Comment by 5nord** [comment]
Wow, that's what I call a quick fix :)

I cannot review and test a the moment, but I like to suggest one improvement though: It would be nice if we could display inline-documentation, when available. For example:
```ttcn3
// run creates a new bash-process and runs cmd string
function run(cmd charstring) { ...}
```
Hover would then additionally display: 
> function run(cmd charstring)  
>  
> run creates a new bash-process and runs cmd string


What do you think?

**How to implement language server request?**
Move desired request stub from [here](https://github.com/nokia/ntt/blob/master/internal/lsp/server_gen.go) to a new file in [here]( https://github.com/nokia/ntt/tree/master/internal/lsp) and  then you can fill in the actuall implementation.
The hover spec is [here](https://microsoft.github.io/language-server-protocol/specification#textDocument_hover). Writing some little tests would be cool (have a look at definition_test.go for inspiration).

**Comment by soham4abc** [comment]
> Wow, that's what I call a quick fix :)
> 
> I cannot review and test a the moment, but I like to suggest one improvement though: It would be nice if we could display inline-documentation, when available. For example:
> 
> ```
> // run creates a new bash-process and runs cmd string
> function run(cmd charstring) { ...}
> ```
> 
> Hover would then additionally display:
> 
> > function run(cmd charstring)
> > run creates a new bash-process and runs cmd string
> 
> What do you think?
> 
> **How to implement language server request?**
> Move desired request stub from [here](https://github.com/nokia/ntt/blob/master/internal/lsp/server_gen.go) to a new file in [here](https://github.com/nokia/ntt/tree/master/internal/lsp) and then you can fill in the actuall implementation.
> The hover spec is [here](https://microsoft.github.io/language-server-protocol/specification#textDocument_hover). Writing some little tests would be cool (have a look at definition_test.go for inspiration).

You can make an issue regarding this. Would be great!

**Comment by soham4abc** [comment]
Any changes required?

**Comment by moosq** [comment]
Encouraging first contribution (y). With your change the 'hover' capability has been enabled but first, communication between LSP client and server needs to be implemented. Otherwise the user will be faced with
`
  [Error - 11:30:32 AM] Request textDocument/hover failed.
  Message: JSON RPC method not found: "Hover" not yet implemented: JSON RPC method not found
  Code: -32601 
`

For this you need to replace `notImplemented("Hover")` with some other functionality in
[internal/lsp/server_gen.go:96](https://github.com/nokia/ntt/blob/74576ad960f1f0fd1f452e2a02e7c214b2c97426/internal/lsp/server_gen.go#L96)

For good examples you can refer to
[internal/lsp/server_gen.go:143](https://github.com/nokia/ntt/blob/74576ad960f1f0fd1f452e2a02e7c214b2c97426/internal/lsp/server_gen.go#L143)

or [internal/lsp/server_gen.go:31](https://github.com/nokia/ntt/blob/74576ad960f1f0fd1f452e2a02e7c214b2c97426/internal/lsp/server_gen.go#L31)

I'm looking forward to your future contributions

**Comment by 5nord** [comment]
hover-error

**Comment by soham4abc** [comment]
> Encouraging first contribution (y). With your change the 'hover' capability has been enabled but first, communication between LSP client and server needs to be implemented. Otherwise the user will be faced with
> `[Error - 11:30:32 AM] Request textDocument/hover failed. Message: JSON RPC method not found: "Hover" not yet implemented: JSON RPC method not found Code: -32601 `
> 
> For this you need to replace `notImplemented("Hover")` with some other functionality in
> [internal/lsp/server_gen.go:96](https://github.com/nokia/ntt/blob/74576ad960f1f0fd1f452e2a02e7c214b2c97426/internal/lsp/server_gen.go#L96)
> 
> For good examples you can refer to
> [internal/lsp/server_gen.go:143](https://github.com/nokia/ntt/blob/74576ad960f1f0fd1f452e2a02e7c214b2c97426/internal/lsp/server_gen.go#L143)
> 
> or [internal/lsp/server_gen.go:31](https://github.com/nokia/ntt/blob/74576ad960f1f0fd1f452e2a02e7c214b2c97426/internal/lsp/server_gen.go#L31)
> 
> I'm looking forward to your future contributions

Thank you for the support! 

I did observed the resources provided by you and did the requested changes! If more changes are required please do request changes! Thank you!!

**Comment by soham4abc** [comment]
@5nord @moosq  Any more changes required?

**Comment by moosq** [comment]
Indeed, there is quite a lot to be done before this can be accepted as done :)
Sorry for the vague wording in the description of this feature. 
What it actually means: when somebody is hovering with the mouse over a reference inside the editor, the definition of this reference shall be shown in the hover text (minimum requirement)
What needs to be done:

1. evaluate the line/column information provided by the language server client.  `func (s *Server) Hover(context.Context, *protocol.HoverParams) (*protocol.Hover, error) ` see `protocol.HoverParams`
2. Query for an identifier at that position. 
3. Do a lookup for a definition
4. if a definition is found, provide the text that make up the definition and send it back to the language server client (that is the return value from the `Hover` function which is of type `protocol.Hover`

So much for the better understanding of what the feature actually means.
Furthermore the provided code should be compile clean and some unit-tests proving that the basic functionality works are in place. For some examples please refer to [symbols_test.go](https://github.com/nokia/ntt/blob/master/internal/ntt/symbols_test.go#L42) or [completion_test.go](https://github.com/nokia/ntt/blob/master/internal/lsp/completion_test.go#L389)

Enjoy, we're looking forward to see some more coding from you

**Comment by soham4abc** [comment]
> Indeed, there is quite a lot to be done before this can be accepted as done :)
> Sorry for the vague wording in the description of this feature. 
> What it actually means: when somebody is hovering with the mouse over a reference inside the editor, the definition of this reference shall be shown in the hover text (minimum requirement)
> What needs to be done:
> 
> 1. evaluate the line/column information provided by the language server client.  `func (s *Server) Hover(context.Context, *protocol.HoverParams) (*protocol.Hover, error) ` see `protocol.HoverParams`
> 2. Query for an identifier at that position. 
> 3. Do a lookup for a definition
> 4. if a definition is found, provide the text that make up the definition and send it back to the language server client (that is the return value from the `Hover` function which is of type `protocol.Hover`
> 
> So much for the better understanding of what the feature actually means.
> Furthermore the provided code should be compile clean and some unit-tests proving that the basic functionality works are in place. For some examples please refer to [symbols_test.go](https://github.com/nokia/ntt/blob/master/internal/ntt/symbols_test.go#L42) or [completion_test.go](https://github.com/nokia/ntt/blob/master/internal/lsp/completion_test.go#L389)
> 
> Enjoy, we're looking forward to see some more coding from you

Sure... I will be working on it!

**Comment by soham4abc** [comment]
> Indeed, there is quite a lot to be done before this can be accepted as done :)
> Sorry for the vague wording in the description of this feature.
> What it actually means: when somebody is hovering with the mouse over a reference inside the editor, the definition of this reference shall be shown in the hover text (minimum requirement)
> What needs to be done:
> 
> 1. evaluate the line/column information provided by the language server client.  `func (s *Server) Hover(context.Context, *protocol.HoverParams) (*protocol.Hover, error) ` see `protocol.HoverParams`
> 2. Query for an identifier at that position.
> 3. Do a lookup for a definition
> 4. if a definition is found, provide the text that make up the definition and send it back to the language server client (that is the return value from the `Hover` function which is of type `protocol.Hover`
> 
> So much for the better understanding of what the feature actually means.
> Furthermore the provided code should be compile clean and some unit-tests proving that the basic functionality works are in place. For some examples please refer to [symbols_test.go](https://github.com/nokia/ntt/blob/master/internal/ntt/symbols_test.go#L42) or [completion_test.go](https://github.com/nokia/ntt/blob/master/internal/lsp/completion_test.go#L389)
> 
> Enjoy, we're looking forward to see some more coding from you

It's okay but could not figure out what changes to make here! I am very very new to this codebase and trying to learn by contributing to opensource! Would be grateful if you mention the exact changes to be done! Sorry for bothering!

**Pull request closed without merging**
